### ISSUE TITLE
Wsea Sewer Path For Bot

### ISSUE THREAD

**Issue by sonic306** [Inix3K/TinTin#7]
From timmy

d|w|w|w|w|w|w|nw|w|nw|n|e|nw|ne|e|w|w|w|w|w|w|sw|sw|e|e|se|e|w|nw|w|w|w|w|nw|n|w|w|w|e|e|e|s|se|se|w|w|sw|sw|e|w|w|w|w|w|e|e|e|e|ne|ne|e|e|nw|e|e|ne|ne|e|e|e|e|e|sw|se|w|s|se|e|se|e|e|sw|se|s|se|s|w|w|w|w|nw|w|w|nw|w|w|w|nw|w|w|sw|ne|n|nw|se|s|e|e|se|e|e|e|ne|ne|e|e|e|e|ne|e|e|e|e|u|say complete

**Comment by sonic306** [comment]
spider
rat
snake
crocodile
cockroach

**Comment by Inix3K** [comment]
This exists, named as 'wsewers.tin'  Killergate pointed out the roomnote wasn't set, so pushing that out on the map.  Closing this issue.
